os: linux
dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install pycodestyle
  - pip install -r requirements.txt > install.log; cat install.log
script:
  - pycodestyle .
  - pytest
  - (cd scripts; ./run_cmds.sh)
